### ISSUE TITLE
[BUG] Does not work without sysguard, which is no always available anymore

### ISSUE THREAD

**Issue by exzombie** [orblazer/plasma-applet-resources-monitor#24]
Hi,

Based on other issues (#6, #8, #18), I know you are aware that ksysguard has been deprecated. I opened this issue to make it clear that it already cannot even be installed on some distros (NixOS 21.11 and [Debian testing](https://github.com/dfaust/plasma-applet-netspeed-widget/issues/28#issuecomment-979801498), for example). Therefore, this widget will need to be ported to the new resource monitoring library sooner rather than later. I'll see if I can help, but my free time is unpredictable, so no promises :)

**Comment by orblazer** [comment]
Hello,
Since v2.6.0 the package `ksysguard` is no longer needed and this widget now use `libksysguard` and this package is an requirement of `ksystemstats` and that is an requirement of `plasma-systemmonitor` and `plasma-workspace`.
So `libksysguard` should be installed by default on recent plasma versions.

**Comment by exzombie** [comment]
:man_facepalming: 
Mea culpa, mea *maxima* culpa. I was testing an outdated version, should have double-checked. After removing the files and reinstalling, it works.

Thanks for maintaining this excellent plasmoid!
