### ISSUE TITLE
[BUG] memory monitor doesn't work at 2.7

### ISSUE THREAD

**Issue by THMonster** [orblazer/plasma-applet-resources-monitor#27]
**Describe the bug**

**To Reproduce**

3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5125031/149252896-54fd87e7-020c-4cab-a780-32f9ff6a4542.png)

**Versions (please complete the following information):**

- Version : 2.7
- KDE Plasma Version : 5.23.5
- KDE Frameworks Version : 5.90.0
- Qt Version : 5.15.2
- Kernel Version : 5.16.0
- OS Type : amd64
- Graphics Platform : x11

**Comment by orblazer** [comment]
Hello, that is strange :confused: 

Could you try if with `2.6.3` that is work ?
If not could you add `print(column, data(indexVar, Sensors.SensorDataModel.Name), value)` before this line ? https://github.com/orblazer/plasma-applet-resources-monitor/blob/0ab30cb1ddf0fa98e9cdf1f09c743c0721affd33/package/contents/ui/components/SensorGraph.qml#L34

Thanks

**Comment by THMonster** [comment]
> Hello, that is strange confused
> 
> Could you try if with `2.6.3` that is work ? If not could you add `print(column, data(indexVar, Sensors.SensorDataModel.Name), value)` before this line ?
> 
> https://github.com/orblazer/plasma-applet-resources-monitor/blob/0ab30cb1ddf0fa98e9cdf1f09c743c0721affd33/package/contents/ui/components/SensorGraph.qml#L34
> 
> Thanks

Added. But how can i get the output info?

**Comment by THMonster** [comment]
oh i got it.
![image](https://user-images.githubusercontent.com/5125031/149328149-abeaaa1e-9919-4021-9598-894c8fabd263.png)

**Comment by orblazer** [comment]
> I tried downgrade. 2.6.3 doesn't work. 2.5.3 works.

That is normal because i have change the system in `2.6.0`.


> oh i got it. ![image](https://user-images.githubusercontent.com/5125031/149328149-abeaaa1e-9919-4021-9598-894c8fabd263.png)

That values look like percent and only CPU...

And i can't reproduce the issue at all, so for that i need some debug :
1. *(optional)* you can use dev env : https://github.com/orblazer/plasma-applet-resources-monitor#contributedebug for easiest debug.
2. Add `print(column, sensors[column])` (my previous line is not great because its follow system language...) before this line https://github.com/orblazer/plasma-applet-resources-monitor/blob/0ab30cb1ddf0fa98e9cdf1f09c743c0721affd33/package/contents/ui/components/SensorGraph.qml#L26
3. Add `print("  ", value)` before this line https://github.com/orblazer/plasma-applet-resources-monitor/blob/0ab30cb1ddf0fa98e9cdf1f09c743c0721affd33/package/contents/ui/components/SensorGraph.qml#L31
4. Print your config by adding `Component.onCompleted: print(JSON.stringify(plasmoid.configuration))` before this line https://github.com/orblazer/plasma-applet-resources-monitor/blob/74a40cfeaad6ded973de605dde97974464708540/package/contents/ui/main.qml#L75

Sorry to ask you to debug that for me :disappointed: and thanks by advance.

**Comment by TiGR** [comment]
Version 2.7.0:

![image](https://user-images.githubusercontent.com/281226/149462992-98696b1c-fc5e-4a7a-936d-76911e41c609.png)

**Comment by orblazer** [comment]
Hello,
Maybe i have found the solution, could you try with that unreleased version ?
[resourcesMonitor-fork-unreleased.zip](https://github.com/orblazer/plasma-applet-resources-monitor/files/7869715/resourcesMonitor-fork-unreleased.zip)

And if that not fix, could you check on `System Monitor` (from `plasma-systemmonitor`) for see if you have the value ?

Thanks.

**Comment by TiGR** [comment]
Okay, memory in percentage now works:

![image](https://user-images.githubusercontent.com/281226/149505657-28b2f8c9-2481-4d7a-86e2-92e4cfa56304.png)

But not when it is not in percentage:

![image](https://user-images.githubusercontent.com/281226/149505704-45db2c7b-18c4-41a6-82f0-6fef1a6f6b82.png)

(I have no swap, just in case)

**Comment by orblazer** [comment]
What is your step to reproduce this case ?

**Comment by TiGR** [comment]
1. Just add the widget, and it looks like this:

![image](https://user-images.githubusercontent.com/281226/149560251-d53e6ad6-90dd-4253-8795-475cdf668fa8.png)

2. Then change to display in percentage:

![image](https://user-images.githubusercontent.com/281226/149560442-d77b309b-c3bb-45a7-a9da-c3e0e40a0cf8.png)

3. Then uncheck the memory in percentage option:

![image](https://user-images.githubusercontent.com/281226/149560493-25677872-59b3-4161-b628-9c28e8d84f2d.png)

**Comment by orblazer** [comment]
I can't reproduce that case :disappointed:  but i have found the reason, the max value is not defined for unknown reason.

I have an question, you have some swap define on the system or is disabled ?

If you have swap, could you add debugs :
- `print(totalMemory)` bellow https://github.com/orblazer/plasma-applet-resources-monitor/blob/master/package/contents/ui/main.qml#L192
- `print(totalSwap)` below https://github.com/orblazer/plasma-applet-resources-monitor/blob/d75e0174a4cc98abb3bf3af3043eb073fc36e524/package/contents/ui/main.qml#L195

Thanks by advance

**Comment by TiGR** [comment]
Jan 15 09:39:45 tigr-TUXEDO plasmashell[1488233]: qml: 33001844736
    Jan 15 09:39:45 tigr-TUXEDO plasmashell[1488233]: qml: 0

**Comment by TiGR** [comment]
@orblazer Thank you. With 2.7.1 finally everything works as intended.
