### ISSUE TITLE
[BUG] Settings has no labels (appearance -> charts -> width/height)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#60]
### Current Behavior

no label on width/height

### Expected Behavior

Know this setting does without hitting apply (or some general idea)
you know if could adjust the vertical margins separate from the horizontal margins that would be nice

### Steps To Reproduce

install widget -> go through settings

### Screenshots

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/564653/afd07feb-7d15-4a2b-a28d-b14e70a2cbd8)

If i could copy/paste this i would have:
![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/564653/a8d9d8c0-350a-455b-a2b4-be54ef34655e)

### Logs

```Text
Not relevant to this bug
```

### Versions

```Markdown
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-46-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
```

**Comment by orblazer** [comment]
Hello,
Do you still have that bug ?

**Comment by GM-Script-Writer-62850** [comment]
upon looking at what that last patch added, i think something is broken more than just the updating process the new setting does not appear

are there any files outside of `.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/`

**Comment by orblazer** [comment]
I think your issue is due to Kirigami (the lib i use for GUI) itself, because in release `5.96.0` it have `Fix checkable labels` (src: https://kde.org/announcements/frameworks/5/5.96.0/). And i'm not sure if it's worth to revert https://github.com/orblazer/plasma-applet-resources-monitor/commit/50817101ae23c1a10c30cc3585f37712154a8ba0 now due to plasma `5.24` is no longer maintained and the release `2.x` of my widget will pass in feature frozen and in "LTS" and only support plasma 5.27.

For the new unreleased feature use `[Appearance]` > `displayment` (stored in `~/.config/plasma-org.kde.plasma.desktop-appletsrc`).

**Comment by GM-Script-Writer-62850** [comment]
now that i upgraded to kubuntu 24.04 this is not a issue (widget version: 2.11.4)
